server:
  port: 7003

#配置eureka
eureka:
  instance:
    hostname: eureka7003.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/