 
spring:
  profiles:
    active: dev
   
---

server:
  port: 7001

#spring配置
spring:
  profiles: dev
  application:
    name: springCloud-config-eureka
    

#配置eureka
eureka:
  instance:
    hostname: eureka7001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---

server:
  port: 7001

#spring配置
spring:
  profiles: test
  application:
    name: springCloud-config-eureka
    

#配置eureka
eureka:
  instance:
    hostname: eureka7001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
       
 